---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: base-image
spec:
  containers:
    - name: runtime
      image: base-image
      command: ["/bin/sh", "-c", "while true ; do date; sleep 1; done;"]
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
