---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # https://github.com/cri-o/cri-o/blob/release-1.31/tutorials/crio-in-kind.md#cri-o-in-kind
    # https://gist.github.com/aojea/bd1fb766302779b77b8f68fa0a81c0f2#file-kind-config-crio-yaml
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          criSocket: unix:///run/crio/crio.sock
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
      - |
        kind: JoinConfiguration
        nodeRegistration:
          criSocket: unix:///var/run/crio/crio.sock
    extraMounts:
      # crio stores containers in /var/run/containers/storage
      - hostPath: /home/runner/.local/share/containers
        containerPath: /var/run/containers
